export default [
  {
    id: 1,
    userId: 1,
    title: "Hello, World!",
    tags: ["hello", "world"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: 2,
    title: "Hello, DynamoDB!",
    tags: ["hello", "dynamodb"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    userId: 3,
    title: "Hello, AWS!",
    tags: ["hello", "aws"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    userId: 4,
    title: "Hello, Serverless!",
    tags: ["hello", "serverless"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    userId: 5,
    title: "Hello, Lambda!",
    tags: ["hello", "lambda"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    userId: 1,
    title: "Hello, API Gateway!",
    tags: ["hello", "api"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    userId: 2,
    title: "Hello, CloudFront!",
    tags: ["hello", "cloud"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    userId: 3,
    title: "Hello, S3!",
    tags: ["hello", "s3"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    userId: 4,
    title: "Hello, RDS!",
    tags: ["hello", "rds"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    userId: 5,
    title: "Hello, DynamoDB!",
    tags: ["hello", "dynamodb"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    userId: 1,
    title: "Hello, Vercel!",
    tags: ["hello", "vercel"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    userId: 2,
    title: "Hello, Netlify!",
    tags: ["hello", "netlify"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 13,
    userId: 3,
    title: "Hello, AWS!",
    tags: ["hello", "aws"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    userId: 4,
    title: "Hello, Serverless!",
    tags: ["hello", "serverless"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 15,
    userId: 5,
    title: "Hello, Lambda!",
    tags: ["hello", "lambda"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 16,
    userId: 1,
    title: "Hello, API Gateway!",
    tags: ["hello", "api"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 17,
    userId: 2,
    title: "Hello, CloudFront!",
    tags: ["hello", "cloud"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 18,
    userId: 3,
    title: "Hello, S3!",
    tags: ["hello", "s3"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 19,
    userId: 4,
    title: "Hello, RDS!",
    tags: ["hello", "rds"],
    createdAt: new Date().toISOString(),
  },
  {
    id: 20,
    userId: 5,
    title: "Hello, DynamoDB!",
    tags: ["hello", "dynamodb"],
    createdAt: new Date().toISOString(),
  },
];
